language: java
os: linux
dist: bionic
jdk: openjdk11
before_install:
  - openssl aes-256-cbc -K $encrypted_92bb71d8d05e_key -iv $encrypted_92bb71d8d05e_iv -in signing_key.gpg.enc -out signing_key.gpg -d
  - gpg2 --version
  - gpg2 --batch --import signing_key.gpg
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then
    MAVEN_CHANGELIST='';
    else
    MAVEN_CHANGELIST='-SNAPSHOT';
    fi;
    export MAVEN_CHANGELIST;
install: skip
script: "./mvnw deploy sonar:sonar -P release --settings settings.xml -Dchangelist=${MAVEN_CHANGELIST} -B"
env:
  global:
    # GPG_PASSPHRASE
    - secure: DB9jDkID1PNwns0FM81ul1XrODBLJ41zjDIOWJ9AJhFOGgkDmaH59dLvPDKNx0tjKm/1SBRGGp/KVsbsUSztcmaJ6GvgP5SH/VJkdrEFh4VWk28JY9stqU3280/Y0l8aG6HWi2Cmd6PTKyMK+rugh05nmB0YhHOyhr/7V8yR+Y77+nZdiBJXc9PCk3w2kYyShM6T62WtfyoJUAvvWffqCp5/SqRGJGwvDOz9u62rZCCeYr2sVUNlnKUqpp5VXnHoLb833f8XrnS4vL3N1OpLaHieJ3AWxxS1ppzwkjYTpQkC4TL0EcFqlKht7AKczxfhLQTFKly+anSOSLx0G3+68+nn+TjQ6oqCZ0k/NyiFC5coX0eTyeE4ygWUt1BoSFG1rnQpajtC/6/N7U2UfKP2rtXgLQQtR/h/m9MkVRKOfakfyuhqAZmv2Upt8ZQmhaNRrZ2uQGGzEeKqGP1P6CcYt4XhfJ++HJ6TafZvezGvPM6Z33FIauGCTfhGHVEXbKlIO7WTCSvpLLHwo3VD+Nf67pTBvfT2Xi7/LUnZS//nYEH5YDcB5jPQyfTs1x06yCZIq0gjXyz4ya3eWm3QDjQJsQ3+KeEr34qTuZ8KqqcjLjYm65svCMdTDV8vf54YgZkN+oPja/Uru0EdoqmoI+OieBMZqQlGWgf/SkS3XDaKfiw=
    # OSSRH_USERNAME
    - secure: s32qxI2kCaj2AnNyAUPmod8WtnMMUvoi6Tp930ZnogqZGNbHB1+IfpuSsNbGn8MStlfjfMIK+cVLy3ytbjzWQxtfOqGv2LYv5b+WWGmKFrgP+/NFT+699bu2QgPU/fIiixR4aeAQsQ1/oAqjz9TJ5LX9uEKYc3o99ifgd/Ij7aA3jAQztuIcHtHb5/wfOwIKr/jMbXbFab/3fIT67XlPWDrK7tpZXY/t3wYscI7clvBzLi3bUeCvljh3Ki3MdP7Q7TExv5zS3eAO3F+MwtAAv1j0QjQBBmX7/WnScKEOV8Yv0oA2PFw6YgkueSpQUZem9YE4PZKlzUgYQRlbGsTnisQXuoJXNn8PC1wp4D++skrWUunlxVJWJjMoRonStidyThm4bIW1d7x0eX5+65S4pUJgx+0c4DsHmgErVKuPLqunTXvtrdNn0XvnTZ4VxQGyjyiEm+8X0so6JTDazUptxBKPDLhoEfVgAEr64f2ctckT8jCfV7RP0nSA+A1y7CvdmkeezbdKNU16AmwelEuBwiXpYye6JSG6SASeZstyz5dsxkEpSdKc1GkbJ/U0rYC+08cApDbmyb15FjBmhDmIs+o8WAGnuF0j78+1qpmr599DEShSzvFb1rQhkRDlIshvWsloRO1qXqqz7mL0qNUcjvx3UD9Ij+IiglP5FnsPXcc=
    # OSSRH_PASSWORD
    - secure: Lu7glX2IMprjsNH9rVCRhyZ28v5ZzJ4Cx21QHvF2fF+Sxjzeipt4fPXKOusX84KlrVKG+AjC7tVzOgKTHos+W8ylIUzAtdLhMGS1ob5EFSCkm1h8Ttff5GO229cM5jG/nAnP80GE4CsGdWyocD2KQDKU5GLbfgNJIeBpvMr5kF1zTutDxoRkwlnvfXTY5t/gd1G2YFWiF8HBJaKbXTiDHqY1wZrbgvOThvBe6C8LjxT5wA5BE2vbf8fm882c+Etn39etOcrP8vjfFABeb6W6puT2zoSmD7TUafm3aWVfsqZtlzfUXUryzu0bA5rK3JQ5dxUM9sGwazx0g1yiGQbHMGtFDgQdWJyDYrQc6GwxWKffoQadNZaDrwqf9zcz4W+xWDybOiAV2bKRyNOdRANX/ZyYUMtoLBROD1UrErH/kR/rBscphd59QPGbygHchZ6umVm3DVrcSpP3rrJpqi8LUu+IsRwHktmHDBAfDDafxFQQe0iJNebi8WeSyyMjatUosH6yOAEYPMpwpYj8kecqwVX6jmOssjXQeKXSuflpfA0dUizVIi+bR+wruWsb30UjkcVn5D+j1cYEsrfANYTG8QtQXV6E4oGXxqLBBtudeE8Jn7/rVTXU3aMYILnUqjGEP0I+HRJEBkFY3qMA2rfjzs9AgSB+bsRTd/9MLKZW+8g=
    # SONARCLOUD_TOKEN
    - secure: S04AigYRfIKbAFsPwgzjlG0yfPfFrw9vfktb4sFxHBv6I40gAj+gyXoNbN+3+vyDkOyh2/Tu7OboI0PMXT9N7fE5vIlqJmV3Iw4KFSFVz+A7Ne3jUKfMZeODA2CwSEtFZupC/tAr0d4N0QLt1AWcPthB3AsWC3F23Wj+ekIonFesaUBDy++8+lt0Ms0SL//+NhMhEaqtKttS2dMRcEZ+jrRnbwnGffdUd8q8cVc4TBb6ZQuf3slGGmSo7SIkqTnkdDoJzTodNB/6vyaD3GJLJluxPgPVfjNv7FtMuW+kEwdDjYCU+eUc7nDzkg7WcLV/+A3bUh96azxhKy/To5LHWFZE9soXB4j3NvuwS6Wkhu4SKMKc8dwaDyRH+ArcUa8so2MNs7a766R4+MeLfQfkbHbvaj93MTyMthYQkkb2qUtTJjDaZ3H1/jKOqQM/vYVcYHRtSt4RhATSETqyExX8kVpIWmiApgGZQssdA7NU9eRM18lU2dGAlbaJcR/8igMo4QIfIrGE49FhoVpR94PUSCJEiRKmQqNtF6A9AvnAAEZKVjWiDVqiScOVV+v42ZlaEjU1iCFbs6XI2q86By6s8XhNyW6oA5xn920DlqFnFmrHLEs9FQnLkZTZBKByJp3zmgufulepBIfPPiD+3H0gX/nT40E4hVJvoWHLaHKfz/8=
cache:
  directories:
    - $HOME/.m2